/**
 * Draws `src/app/favicon.ico` as a small-size cut of the desktop app's icon.
 *
 * The icon itself lives in `ensemblr-hq/ensemblr` — `assets/icon.png` and
 * `assets/icon.svg`, generated by that repo's `scripts/icon-art.mjs`. It is
 * copied into `src/app/` verbatim, and every constant below is that script's,
 * so the tab, the home screen and the Dock stay one mark. The one deliberate
 * departure is documented at `FRAMES`.
 *
 * Why not just downsample the 1024px art? Tried it; it does not survive. That
 * mark is a 5x7 dot grid with a ±0.27-cell chromatic split and a 26px bloom,
 * all sitting inside 80% of its canvas. Resample it to 16px and the grid, the
 * split and the padding average into one pink smudge. A favicon is drawn at
 * 16, 20 or 32 *device* pixels with no subpixel slack, so this redraws the
 * glyph at each size instead, on integer coordinates.
 *
 * What survives the cut, and what does not:
 *
 *   kept     the squircle, the dot grid, the cyan/red chromatic split
 *   dropped  the bloom — 26px of blur at 1024 is a quarter-pixel at 16
 *   dropped  the rim — it exists to hold an edge on a dark macOS Dock
 *   changed  the squircle is full-bleed, not inset (see `FRAMES`)
 *
 * Three frames, which is the set an .ico is still asked for:
 *
 *   16  browser tabs, and the size almost every visitor actually sees
 *   32  retina tabs, bookmark bars, the Windows taskbar
 *   48  Windows site shortcuts
 *
 * Anything larger is served by `icon.svg` and `apple-icon.png`, which Next
 * links from `<head>` alongside this file. Run `bun run gen:favicon`; the
 * output is committed, and `generate-favicon.test.ts` fails if it drifts.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildGlyphPixels, GLYPH_HEIGHT, GLYPH_WIDTH } from '../src/lib/glyphs';

interface Colour {
	readonly r: number;
	readonly g: number;
	readonly b: number;
}

/* Verbatim from `scripts/icon-colors.mjs` in the app repo. */
const CANVAS: Colour = { r: 0x0a, g: 0x07, b: 0x07 };
const INK: Colour = { r: 0xe4, g: 0xe1, b: 0xdd };
const GHOST_CYAN: Colour = { r: 0x22, g: 0xd3, b: 0xee };
const GHOST_RED: Colour = { r: 0xff, g: 0x2e, b: 0x63 };

/* Verbatim from `scripts/icon-art.mjs` in the app repo. */
const SQUIRCLE_EXPONENT = 5;
const GHOST_OFFSET_RATIO = 0.27;
const GHOST_OPACITY = 0.7;
const BLOCK_RADIUS_RATIO = 0.16;

/**
 * Subsamples per axis. The ink grid is already pixel-aligned and needs none of
 * this; the squircle's shoulder and the chromatic ghosts do, and the ghosts are
 * the reason it is 8 rather than 4 — a 0.54px cyan offset at 16 exists *only*
 * as a partially-covered edge pixel, so the sampling has to be fine enough to
 * resolve it into a tint instead of rounding it away.
 */
const SUPERSAMPLE = 8;

interface Frame {
	/** Edge length in device pixels. */
	readonly size: number;
	/** Grid pitch: one bitmap cell, in device pixels. */
	readonly cell: number;
	/** Lit block inside that cell. Smaller than `cell` leaves the grid gap. */
	readonly block: number;
	/** Chromatic split, in device pixels. See `FRAMES`. */
	readonly ghost: number;
	/** Opacity of the split. See `FRAMES`. */
	readonly ghostOpacity: number;
}

/*
 * The one place this departs from the app icon, and it is a deliberate crop.
 *
 * The app icon spends 20% of its canvas on the margin macOS requires and
 * another 40% of what is left on the padding inside the squircle, so the `E`
 * covers about a fifth of the image. That is right on a Dock and wrong in a
 * browser tab, which supplies its own padding: at 16px the same proportions
 * leave the glyph nine pixels tall and the mark stops being readable. So the
 * squircle goes full-bleed and the glyph is scaled up to meet it.
 *
 * Every number here divides the canvas exactly — 5 cells across and 7 down land
 * on whole pixels at all three sizes — because a half-pixel edge on a 16px icon
 * is a blurred one. `block` keeps the app's 0.76-of-a-cell ratio where the
 * arithmetic allows: 3/4 at 32, 5/6 at 48. At 16 there is no room for a gap at
 * all — one pixel of gap out of two is half the stroke — so the blocks run
 * together and the chromatic split is the only thing left saying "dot grid".
 *
 * The split is the other thing that cannot be copied by ratio. At 1024 the
 * ghosts are 19px of saturated cyan and red against black, read as an edge
 * because they are 2% of the image; scaled to `GHOST_OFFSET_RATIO * cell` they
 * become 0.54px at 16, and a 54%-covered pixel of #ff2e63 over #0a0707 is not
 * a fringe, it is a maroon block sitting beside a two-pixel stroke. So the
 * offsets are pulled in and the opacity down until the ghost reads the way it
 * does on the Dock — as colour on the edge of the glyph rather than a second
 * glyph. It stays at full strength only at 48, where a pixel is small enough
 * relative to the mark for the app's own numbers to hold.
 */
const FRAMES: readonly Frame[] = [
	{ size: 16, cell: 2, block: 2, ghost: 0.4, ghostOpacity: 0.5 },
	{ size: 32, cell: 4, block: 3, ghost: 0.9, ghostOpacity: 0.6 },
	{
		size: 48,
		cell: 6,
		block: 5,
		ghost: 6 * GHOST_OFFSET_RATIO,
		ghostOpacity: GHOST_OPACITY,
	},
];

const GLYPH = buildGlyphPixels('E');

function insideSquircle(x: number, y: number, size: number): boolean {
	const radius = size / 2;
	const u = Math.abs((x - radius) / radius);
	const v = Math.abs((y - radius) / radius);
	return u ** SQUIRCLE_EXPONENT + v ** SQUIRCLE_EXPONENT <= 1;
}

function insideRoundedBlock(
	x: number,
	y: number,
	left: number,
	top: number,
	side: number,
	radius: number,
): boolean {
	if (x < left || x >= left + side || y < top || y >= top + side) {
		return false;
	}
	if (radius <= 0) {
		return true;
	}
	// Only the four corner squares can fall outside; the cross through the
	// middle is always in.
	const dx = Math.max(left + radius - x, x - (left + side - radius), 0);
	const dy = Math.max(top + radius - y, y - (top + side - radius), 0);
	return dx * dx + dy * dy <= radius * radius;
}

function mix(base: Colour, over: Colour, alpha: number): Colour {
	return {
		r: base.r + (over.r - base.r) * alpha,
		g: base.g + (over.g - base.g) * alpha,
		b: base.b + (over.b - base.b) * alpha,
	};
}

/** Renders one frame as top-down RGBA8. */
function renderFrame(frame: Frame): Uint8Array {
	const { size, cell, block, ghost, ghostOpacity } = frame;
	const radius = Math.round(block * BLOCK_RADIUS_RATIO);
	/*
	 * Centred on the drawn extent rather than the grid, and floored so the ink
	 * lands on whole pixels. The residual half-pixel goes to the right and
	 * bottom margins, where the cyan and red ghosts spill anyway.
	 */
	const originX = Math.floor((size - ((GLYPH_WIDTH - 1) * cell + block)) / 2);
	const originY = Math.floor((size - ((GLYPH_HEIGHT - 1) * cell + block)) / 2);

	/** Painter's order, matching `buildGlyphMvg` in the app repo. */
	const layers: readonly { colour: Colour; alpha: number; dx: number }[] = [
		{ colour: GHOST_CYAN, alpha: ghostOpacity, dx: -ghost },
		{ colour: GHOST_RED, alpha: ghostOpacity, dx: ghost },
		{ colour: INK, alpha: 1, dx: 0 },
	];

	const pixels = new Uint8Array(size * size * 4);
	const step = 1 / SUPERSAMPLE;
	const total = SUPERSAMPLE * SUPERSAMPLE;

	for (let y = 0; y < size; y += 1) {
		for (let x = 0; x < size; x += 1) {
			let opaque = 0;
			let r = 0;
			let g = 0;
			let b = 0;

			for (let sy = 0; sy < SUPERSAMPLE; sy += 1) {
				for (let sx = 0; sx < SUPERSAMPLE; sx += 1) {
					const px = x + (sx + 0.5) * step;
					const py = y + (sy + 0.5) * step;
					if (!insideSquircle(px, py, size)) {
						continue;
					}

					let colour = CANVAS;
					for (const layer of layers) {
						const lit = GLYPH.some((pixel) =>
							insideRoundedBlock(
								px,
								py,
								originX + pixel.x * cell + layer.dx,
								originY + pixel.y * cell,
								block,
								radius,
							),
						);
						if (lit) {
							colour = mix(colour, layer.colour, layer.alpha);
						}
					}

					r += colour.r;
					g += colour.g;
					b += colour.b;
					opaque += 1;
				}
			}

			if (opaque === 0) {
				continue;
			}
			const offset = (y * size + x) * 4;
			pixels[offset] = Math.round(r / opaque);
			pixels[offset + 1] = Math.round(g / opaque);
			pixels[offset + 2] = Math.round(b / opaque);
			pixels[offset + 3] = Math.round((opaque / total) * 255);
		}
	}

	return pixels;
}

/**
 * Packs one frame as a 32-bit BMP, which is what an .ico entry holds.
 *
 * PNG-compressed entries are legal and smaller, but only above Windows Vista;
 * at these sizes the whole file is under 15KB uncompressed, so the older,
 * duller encoding costs nothing and can be read by anything. Two quirks of the
 * format worth knowing before editing this: the header declares double the
 * real height (it covers the colour bitmap *and* the legacy 1-bit AND mask
 * stacked underneath it), and rows run bottom-up.
 */
function encodeBmp(rgba: Uint8Array, size: number): Uint8Array {
	const maskStride = (((size + 31) / 32) | 0) * 4;
	const colourBytes = size * size * 4;
	const maskBytes = maskStride * size;
	const buffer = new Uint8Array(40 + colourBytes + maskBytes);
	const view = new DataView(buffer.buffer);

	view.setUint32(0, 40, true); // header size
	view.setInt32(4, size, true); // width
	view.setInt32(8, size * 2, true); // height, colour + mask
	view.setUint16(12, 1, true); // planes
	view.setUint16(14, 32, true); // bits per pixel
	view.setUint32(16, 0, true); // BI_RGB, uncompressed
	view.setUint32(20, colourBytes + maskBytes, true);

	for (let y = 0; y < size; y += 1) {
		const sourceRow = (size - 1 - y) * size * 4;
		for (let x = 0; x < size; x += 1) {
			const source = sourceRow + x * 4;
			const target = 40 + (y * size + x) * 4;
			buffer[target] = rgba[source + 2]; // B
			buffer[target + 1] = rgba[source + 1]; // G
			buffer[target + 2] = rgba[source]; // R
			buffer[target + 3] = rgba[source + 3]; // A

			// A set bit means "leave the pixel behind this one alone", which is
			// how a renderer that ignores the alpha channel still gets a corner.
			if (rgba[source + 3] < 128) {
				const bit = 40 + colourBytes + y * maskStride + (x >> 3);
				buffer[bit] |= 0x80 >> (x & 7);
			}
		}
	}

	return buffer;
}

function encodeIco(frames: readonly { size: number; body: Uint8Array }[]) {
	const directory = 6 + frames.length * 16;
	const buffer = new Uint8Array(
		directory + frames.reduce((sum, frame) => sum + frame.body.length, 0),
	);
	const view = new DataView(buffer.buffer);

	view.setUint16(0, 0, true); // reserved
	view.setUint16(2, 1, true); // type: icon
	view.setUint16(4, frames.length, true);

	let offset = directory;
	frames.forEach((frame, index) => {
		const entry = 6 + index * 16;
		buffer[entry] = frame.size === 256 ? 0 : frame.size;
		buffer[entry + 1] = frame.size === 256 ? 0 : frame.size;
		buffer[entry + 2] = 0; // palette size, 0 for truecolour
		buffer[entry + 3] = 0; // reserved
		view.setUint16(entry + 4, 1, true); // planes
		view.setUint16(entry + 6, 32, true); // bits per pixel
		view.setUint32(entry + 8, frame.body.length, true);
		view.setUint32(entry + 12, offset, true);
		buffer.set(frame.body, offset);
		offset += frame.body.length;
	});

	return buffer;
}

/**
 * The whole file, in memory. Pure and deterministic on purpose: the committed
 * `.ico` is a build artifact checked into the repo, and `generate-favicon.test.ts`
 * re-runs this to prove the bytes on disk are still the ones this script would
 * produce. Without that, editing the bitmap silently leaves a stale icon in
 * every visitor's tab until someone remembers to re-run the generator.
 */
export function buildFavicon(): Uint8Array {
	if (GLYPH.length === 0) {
		throw new Error(
			'No bitmap for "E" in src/lib/glyphs.ts — nothing to draw.',
		);
	}
	return encodeIco(
		FRAMES.map((frame) => ({
			size: frame.size,
			body: encodeBmp(renderFrame(frame), frame.size),
		})),
	);
}

export const FAVICON_PATH = join(
	import.meta.dir,
	'..',
	'src',
	'app',
	'favicon.ico',
);

if (import.meta.main) {
	const encoded = buildFavicon();
	writeFileSync(FAVICON_PATH, encoded);
	console.info(
		`✓ src/app/favicon.ico — ${FRAMES.map((frame) => `${frame.size}x${frame.size}`).join(', ')}, ${encoded.length} bytes`,
	);
}
