/**
 * Cuts `src/app/favicon.ico` out of `src/app/apple-icon.png`.
 *
 * The icon itself lives in `ensemblr-hq/ensemblr` — `assets/icon.png` and
 * `assets/icon.svg`, generated by that repo's `scripts/icon-art.mjs`. It is
 * copied into `src/app/` verbatim, and this script does exactly two things to
 * it: resize, then re-encode. No redraw, no recolour, no crop. The tab, the
 * home screen and the Dock are the same picture at different sizes.
 *
 * That is a deliberate reversal. This script used to redraw the mark at each
 * favicon size — full-bleed squircle, no bloom, no rim, integer coordinates —
 * because the art is built for a Dock and does not survive a 64:1 downsample:
 * it spends 20% of the canvas on the margin macOS wants and 40% of the rest on
 * padding, so the `E` covers about a fifth of the image and a 16px cut of it is
 * a dim smudge. A redraw reads better at 16. It is also, unavoidably, a
 * different picture from the one shipping in the Dock, and keeping the two in
 * step was a manual job nothing checked. Fidelity won.
 *
 * What that costs, so nobody rediscovers it as a bug:
 *
 *   16  legible as a dark tile with a pale `E`; the dot grid averages away
 *   32  the grid, the gaps and the chromatic split all read
 *   48  effectively the art
 *
 * Chrome and Firefox never see any of this — Next links `icon.svg` alongside
 * this file and they prefer it, so the 16px cut is what Safari and the Windows
 * taskbar fall back to.
 *
 * Three frames, which is the set an .ico is still asked for:
 *
 *   16  browser tabs, and the size almost every visitor actually sees
 *   32  retina tabs, bookmark bars, the Windows taskbar
 *   48  Windows site shortcuts
 *
 * Anything larger is served by `icon.svg` and `apple-icon.png`, which Next
 * links from `<head>` alongside this file. Run `bun run gen:favicon`; the
 * output is committed, and `generate-favicon.test.ts` fails if it drifts.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import sharp from 'sharp';

const ROOT = join(import.meta.dir, '..');

/** The app icon, copied verbatim from `assets/icon.png` in the app repo. */
export const SOURCE_PATH = join(ROOT, 'src', 'app', 'apple-icon.png');

export const FAVICON_PATH = join(ROOT, 'src', 'app', 'favicon.ico');

/** Edge lengths, in device pixels, of the frames the .ico carries. */
export const SIZES: readonly number[] = [16, 32, 48];

/**
 * Lanczos over a windowed sinc, which is sharp's default and the one that keeps
 * the most of a 26px bloom and a ±0.27-cell chromatic split. Pinned here rather
 * than left implicit because the committed bytes are asserted against it.
 */
export const KERNEL = 'lanczos3';

/**
 * Resizes the source to one square frame of top-down RGBA8.
 *
 * `fit: 'fill'` is the honest setting for a source that is already square: it
 * says "no crop, no letterbox" outright instead of relying on the aspect ratios
 * agreeing, so a source that stopped being square fails the check below rather
 * than silently losing an edge of the mark.
 */
export async function renderFrame(size: number): Promise<Uint8Array> {
	const { data, info } = await sharp(SOURCE_PATH)
		.resize(size, size, { fit: 'fill', kernel: KERNEL })
		.raw()
		.toBuffer({ resolveWithObject: true });

	if (info.channels !== 4) {
		throw new Error(
			`${SOURCE_PATH} resized to ${info.channels} channels, not RGBA — the squircle corners need an alpha channel.`,
		);
	}
	return new Uint8Array(data);
}

/**
 * Packs one frame as a 32-bit BMP, which is what an .ico entry holds.
 *
 * PNG-compressed entries are legal and smaller, but only above Windows Vista;
 * at these sizes the whole file is under 15KB uncompressed, so the older,
 * duller encoding costs nothing and can be read by anything. Two quirks of the
 * format worth knowing before editing this: the header declares double the
 * real height (it covers the colour bitmap *and* the legacy 1-bit AND mask
 * stacked underneath it), and rows run bottom-up.
 */
function encodeBmp(rgba: Uint8Array, size: number): Uint8Array {
	const maskStride = (((size + 31) / 32) | 0) * 4;
	const colourBytes = size * size * 4;
	const maskBytes = maskStride * size;
	const buffer = new Uint8Array(40 + colourBytes + maskBytes);
	const view = new DataView(buffer.buffer);

	view.setUint32(0, 40, true); // header size
	view.setInt32(4, size, true); // width
	view.setInt32(8, size * 2, true); // height, colour + mask
	view.setUint16(12, 1, true); // planes
	view.setUint16(14, 32, true); // bits per pixel
	view.setUint32(16, 0, true); // BI_RGB, uncompressed
	view.setUint32(20, colourBytes + maskBytes, true);

	for (let y = 0; y < size; y += 1) {
		const sourceRow = (size - 1 - y) * size * 4;
		for (let x = 0; x < size; x += 1) {
			const source = sourceRow + x * 4;
			const target = 40 + (y * size + x) * 4;
			buffer[target] = rgba[source + 2]; // B
			buffer[target + 1] = rgba[source + 1]; // G
			buffer[target + 2] = rgba[source]; // R
			buffer[target + 3] = rgba[source + 3]; // A

			// A set bit means "leave the pixel behind this one alone", which is
			// how a renderer that ignores the alpha channel still gets a corner.
			if (rgba[source + 3] < 128) {
				const bit = 40 + colourBytes + y * maskStride + (x >> 3);
				buffer[bit] |= 0x80 >> (x & 7);
			}
		}
	}

	return buffer;
}

function encodeIco(frames: readonly { size: number; body: Uint8Array }[]) {
	const directory = 6 + frames.length * 16;
	const buffer = new Uint8Array(
		directory + frames.reduce((sum, frame) => sum + frame.body.length, 0),
	);
	const view = new DataView(buffer.buffer);

	view.setUint16(0, 0, true); // reserved
	view.setUint16(2, 1, true); // type: icon
	view.setUint16(4, frames.length, true);

	let offset = directory;
	frames.forEach((frame, index) => {
		const entry = 6 + index * 16;
		buffer[entry] = frame.size === 256 ? 0 : frame.size;
		buffer[entry + 1] = frame.size === 256 ? 0 : frame.size;
		buffer[entry + 2] = 0; // palette size, 0 for truecolour
		buffer[entry + 3] = 0; // reserved
		view.setUint16(entry + 4, 1, true); // planes
		view.setUint16(entry + 6, 32, true); // bits per pixel
		view.setUint32(entry + 8, frame.body.length, true);
		view.setUint32(entry + 12, offset, true);
		buffer.set(frame.body, offset);
		offset += frame.body.length;
	});

	return buffer;
}

/** Rejects a source that cannot be resized into these frames without a crop. */
async function assertSquareSource(): Promise<void> {
	const { width, height } = await sharp(SOURCE_PATH).metadata();
	if (!width || !height) {
		throw new Error(`Could not read the dimensions of ${SOURCE_PATH}.`);
	}
	if (width !== height) {
		throw new Error(
			`${SOURCE_PATH} is ${width}x${height}; the favicon is square and this script only resizes, so a non-square source would have to be cropped.`,
		);
	}
	const largest = Math.max(...SIZES);
	if (width < largest) {
		throw new Error(
			`${SOURCE_PATH} is ${width}px, smaller than the ${largest}px frame — this script only downsamples.`,
		);
	}
}

/**
 * The whole file, in memory. Pure and deterministic on purpose: the committed
 * `.ico` is a build artifact checked into the repo, and `generate-favicon.test.ts`
 * re-runs this to prove the bytes on disk are still the ones this script would
 * produce. Without that, replacing `apple-icon.png` silently leaves a stale icon
 * in every visitor's tab until someone remembers to re-run the generator.
 */
export async function buildFavicon(): Promise<Uint8Array> {
	await assertSquareSource();
	const frames = await Promise.all(
		SIZES.map(async (size) => ({
			size,
			body: encodeBmp(await renderFrame(size), size),
		})),
	);
	return encodeIco(frames);
}

if (import.meta.main) {
	const encoded = await buildFavicon();
	writeFileSync(FAVICON_PATH, encoded);
	console.info(
		`✓ src/app/favicon.ico — ${SIZES.map((size) => `${size}x${size}`).join(', ')}, ${encoded.length} bytes, resized from src/app/apple-icon.png`,
	);
}
